name: lyell_project
repository: https://github.com/DarwinFramework/lyell

environment:
  sdk: '>=3.9.0 <4.0.0'

workspace:
  - packages/lyell
  - packages/lyell_gen

dev_dependencies:
  melos: ^7.1.0

melos:
  scripts:
    copy-readme:
      name: copy-readme
      description: 'Copies the root-Readme to the dogs package'
      run: cp README.md packages/lyell/README.md && cp README.md packages/lyell_gen/README.md
    analyze:
      name: analyze
      description: 'Runs the dart analyzer'
      run: dart analyze .
      exec:
        concurrency: 1
    format:
      name: format
      description: 'Runs the dart formatter'
      run: dart format .
      exec:
        concurrency: 1