name: lyell
description: Generator utilities used by darwin and dogs..
version: 1.4.4
repository: https://github.com/DarwinFramework/lyell

environment:
  sdk: '>=3.5.0 <4.0.0'

resolution: workspace

dependencies:
  collection: ^1.17.1

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.15
