name: lyell_gen
description: Generator utilities used by darwin and dogs.
version: 1.2.4+1
repository: https://github.com/DarwinFramework/lyell

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  build: '>=2.0.0 <3.0.0'
  analyzer: ">=2.0.0 <7.0.0"
  source_gen: '>=1.0.0 <=2.0.0'
  collection: '>=1.15.0 <2.0.0'
  crypto: '>=3.0.0 <4.0.0'
  glob: '>=2.0.0 <3.0.0'
  path: '>=1.8.0 <2.0.0'
  code_builder: '>=4.3.0 <5.0.0'
  dart_style: '>=2.2.4 <3.0.0'
  lyell: ^1.1.0
  mutex: ^3.1.0
  duffer: ^2.3.2
dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.1
