name: lyell_gen
description: Generator utilities used by darwin and dogs.
version: 3.0.9
repository: https://github.com/DarwinFramework/lyell

environment:
  sdk: '>=3.5.0 <4.0.0'

resolution: workspace

dependencies:
  build: ^3.0.2
  analyzer: ^8.1.1
  source_gen: ^4.0.0
  crypto: ^3.0.6
  glob: ^2.1.3
  path: ^1.9.1
  code_builder: ^4.10.1
  dart_style: ^3.1.2
  collection: ^1.19.1

  lyell: ^1.4.5
  mutex: ^3.1.0
  duffer: ^2.3.2
dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.15
