name: generator
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  build: ^3.0.2
  analyzer: ^7.7.1
  source_gen: ^3.1.0
  crypto: ^3.0.6
  glob: ^2.1.3
  path: ^1.9.1
  code_builder: ^4.10.1
  dart_style: ^3.1.1
  collection: ^1.19.1

  lyell: any
  lyell_gen: any

dev_dependencies:
  lints: ^2.0.0
